Add fix to fast fail

diff --git a/truss/templates/base.Dockerfile.jinja b/truss/templates/base.Dockerfile.jinja
--- a/truss/templates/base.Dockerfile.jinja
+++ b/truss/templates/base.Dockerfile.jinja
@@ -4,12 +4,12 @@ FROM {{base_image_name_and_tag}}
 {% block fail_fast %}
 RUN grep -w 'ID=debian\|ID_LIKE=debian' /etc/os-release || { echo "ERROR: Supplied base image is not a debian image"; exit 1; }
 RUN pythonVersion=$(echo $(command -v python >/dev/null 2>&1 && python --version || python3 --version) | cut -d" " -f2 | cut -d"." -f1,2) \
-    && echo $pythonVersion | grep -E '3\.[0-9]|10\.[0-9][0-9]' \
+    && echo $pythonVersion | grep -E '3\.[0-9]|10|11\.[0-9][0-9]' \
     && apt-get update && ( apt-get install -y --no-install-recommends python$pythonVersion-venv || apt-get install -y --no-install-recommends python3-venv )  \
     && apt-get autoremove -y \
     && apt-get clean -y \
     && rm -rf /var/lib/apt/lists/* \
-    || { echo "ERROR: Supplied base image does not have 3.8 <= python <= 3.10"; exit 1; }
+    || { echo "ERROR: Supplied base image does not have 3.8 <= python <= 3.11"; exit 1; }
 {% endblock %}
 
 RUN pip install --upgrade pip --no-cache-dir \
