custom base image support (#268)
* progress for supporting custom base images (needs testing)

* wrap in conditional

* add support for custom base image

* use subtemplate for build + additional external image build test case

* support for python and python3 checks

diff --git a/truss/templates/base.Dockerfile.jinja b/truss/templates/base.Dockerfile.jinja
--- a/truss/templates/base.Dockerfile.jinja
+++ b/truss/templates/base.Dockerfile.jinja
@@ -1,6 +1,17 @@
 ARG PYVERSION={{config.python_version}}
 FROM {{base_image_name_and_tag}}
 
+{% block fail_fast %}
+        RUN grep -w 'ID=debian\|ID_LIKE=debian' /etc/os-release || { echo "ERROR: Supplied base image is not a debian image"; exit 1; }
+        RUN which python && python --version | grep -E '3\.[0-9]|10\.[0-9][0-9]' || \
+            which python3 && python3 --version | grep -E '3\.[0-9]|10\.[0-9][0-9]' || \
+            { echo "ERROR: Supplied base image does not have 3.8 <= python <= 3.10"; exit 1; }
+{% endblock %}
+
+{% if config.base_image %}
+    {% include truss_build_template_path %}
+{% endif %}
+
 RUN pip install --upgrade pip --no-cache-dir \
     && rm -rf /root/.cache/pip
 {% if config.model_framework.value == 'huggingface_transformer' %}
