0.0.1

diff --git a/.github/workflows/baseten-performance-client-nodejs.yml b/.github/workflows/baseten-performance-client-nodejs.yml
--- a/.github/workflows/baseten-performance-client-nodejs.yml
+++ b/.github/workflows/baseten-performance-client-nodejs.yml
@@ -239,9 +239,6 @@ jobs:
         settings:
           - host: macos-latest
             target: x86_64-apple-darwin
-          # TODO: reenable windows release.
-           # 'perl' reported failure with exit code: 2
-              # Command failed: "perl" "./Configure" "--prefix=D:/a/truss/truss/baseten-performance-client/target/i686-pc-windows-msvc/release/build/openssl-sys-653f4201b14b98a2/out/openssl-build/install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-shared" "no-module" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-capieng" "no-asm" "VC-WIN32"
           - host: windows-latest
             target: x86_64-pc-windows-msvc
         node:
@@ -339,7 +336,6 @@ jobs:
         run: docker run --rm -v $(pwd):/build -w /build/ node:${{ matrix.node }}-alpine sh -c "cp baseten-performance-client/node_bindings/*.node . && yarn test"
   test-linux-aarch64-gnu-binding:
     name: Test bindings on aarch64-unknown-linux-gnu - node@${{ matrix.node }}
-    if: false # relative path issue when testing
     needs:
       - build
     strategy:
@@ -373,7 +369,7 @@ jobs:
         uses: addnab/docker-run-action@v3
         with:
           image: node:${{ matrix.node }}-slim
-          options: '--platform linux/arm64 -v ${{ github.workspace }}:/build -w /build/baseten-performance-client/node_bindings'
+          options: '--platform linux/arm64 -v ${{ github.workspace }}:/build -w /build/'
           run: |
             set -e
             cp baseten_performance_client/node_bindings/*.node .
@@ -448,9 +444,11 @@ jobs:
         uses: addnab/docker-run-action@v3
         with:
           image: node:${{ matrix.node }}-bullseye-slim
-          options: '--platform linux/arm/v7 -v ${{ github.workspace }}:/build -w /build/baseten-performance-client/node_bindings'
+          options: '--platform linux/arm/v7 -v ${{ github.workspace }}:/build -w /build/'
           run: |
             set -e
+            # cannot stat baseten_performance_client/node_bindings/*.node: No such file or directory
+            # --
             cp baseten_performance_client/node_bindings/*.node .
             yarn test
             ls -la
@@ -503,7 +501,7 @@ jobs:
     needs:
       # - build-freebsd
       - test-macOS-windows-binding
-      # - test-linux-x64-gnu-binding
+      - test-linux-x64-gnu-binding
       - test-linux-x64-musl-binding
       # - test-linux-aarch64-gnu-binding
       # - test-linux-aarch64-musl-binding
@@ -542,6 +540,6 @@ jobs:
             echo "Not a release, skipping publish"
           fi
           echo "publishing release anyways with --next for debugging. "
-          npm publish --access public --tag next || echo "publishing failed."
+          npm publish --access public || echo "publishing failed."
         env:
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
