Diff

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -1,4 +1,4 @@
-name: PR
+name: PR - pre-commit
 
 on:
   pull_request:
@@ -11,7 +11,7 @@ jobs:
   lint:
     runs-on: ubuntu-20.04
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           lfs: true
       - uses: ./.github/actions/setup-python/
@@ -23,35 +23,11 @@ jobs:
           poetry run ruff check .
           poetry run ruff format . --check
 
-  enforce-chains-example-docs-sync:
-    runs-on: ubuntu-20.04
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          lfs: true
-      - name: Check if chains examples were modified
-        id: check_files
-        run: |
-          if git diff --name-only origin/main | grep -q '^truss-chains/examples/.*'; then
-            echo "::set-output name=docs_needed::true"
-          else
-            echo "::set-output name=docs_needed::false"
-          fi
-
-      - name: Enfore acknoledgement in PR description
-        if: steps.check_files.outputs.docs_needed == 'true'
-        run: |
-          DESCRIPTION=$(jq -r .body < "${GITHUB_EVENT_PATH}")
-          if [[ "$DESCRIPTION" != *"UPDATE_DOCS=done"* && "$DESCRIPTION" != *"UPDATE_DOCS=not_needed"* ]]; then
-            echo "Chains examples were modified, in this case the documentation at https://github.com/basetenlabs/docs.baseten.co/tree/main/chains might need to be updated. Add a tag UPDATE_DOCS={done|not_needed} to the PR description to aknwonledge."
-            exit 1
-          fi
-
   test:
     timeout-minutes: 30
     runs-on: ubuntu-20.04
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           lfs: true
       - uses: ./.github/actions/setup-python/
@@ -67,3 +43,33 @@ jobs:
         with:
           use-verbose-mode: "yes"
           folder-path: "docs"
+
+
+  enforce-chains-example-docs-sync:
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          lfs: true
+          fetch-depth: 2
+      - name: Fetch main branch
+        run: git fetch origin main
+      - name: Check if chains examples were modified
+        id: check_files
+        run: |
+          if git diff --name-only origin/main | grep -q '^truss-chains/examples/.*'; then
+            echo "chains_docs_update_needed=true" >> $GITHUB_ENV
+            echo "Chains examples were modified."
+          else
+            echo "chains_docs_update_needed=false" >> $GITHUB_ENV
+            echo "Chains examples were not modified."
+          fi
+
+      - name: Enforce acknowledgment in PR description
+        if: env.chains_docs_update_needed == 'true'
+        run: |
+          DESCRIPTION="${{ github.event.pull_request.body }}"
+          if [[ "$DESCRIPTION" != *"UPDATE_DOCS=done"* && "$DESCRIPTION" != *"UPDATE_DOCS=not_needed"* ]]; then
+            echo "::error file=truss-chains/examples/::Chains examples were modified, in this case the documentation at https://github.com/basetenlabs/docs.baseten.co/tree/main/chains might need to be updated. Add a tag UPDATE_DOCS={done|not_needed} to the PR description to acknowledge."
+            exit 1
+          fi
