fix build: truss-transfer-cli (#1321)
* fix arm code

* update readme

* add to truss-transfer test

* add env variable

* update docker option

* no asm

* add musl-gcc

* fix target

* update  apt-get install sudo

* and musl-gcc

* add aarch64 support

* fix test

* cargo ring update

* reset reqwest

* cargo update

* update cargo toml

* push split tls

* reset partial cargo

* arm skip v7

* add default tls

* new cargo file

* add cargo toml

* add cargo lock

* add writeext

* forgot featrue default

diff --git a/.github/workflows/truss-transfer-test.yml b/.github/workflows/truss-transfer-test.yml
--- a/.github/workflows/truss-transfer-test.yml
+++ b/.github/workflows/truss-transfer-test.yml
@@ -55,3 +55,28 @@ jobs:
             echo "❌ Test failed: output directory not created."
             exit 1
           fi
+
+      ## CLI direct install
+      - name: Install musl-tools
+        run: sudo apt-get update && sudo apt-get install -y musl-tools
+
+      - name: Install Rust with musl target
+        uses: actions-rs/toolchain@v1
+        with:
+          toolchain: stable
+          override: true
+          components: rust-src
+
+      - name: Add musl Target
+        run: rustup target add x86_64-unknown-linux-musl
+
+      - name: Build Statically Linked CLI Binary
+        run: |
+          apt-get update && apt-get install -y musl-tools musl-gcc
+          cargo build --release --target x86_64-unknown-linux-musl --features cli --bin truss_transfer_cli
+          chmod +x target/x86_64-unknown-linux-musl/release/truss_transfer_cli
+          ./target/x86_64-unknown-linux-musl/release/truss_transfer_cli "./tmp_cli_no_fs_cache/test"
+          if [ ! -d "./tmp_cli_no_fs_cache/test" ]; then
+            echo "❌ Test failed: output directory not created."
+            exit 1
+          fi
